create table categories(
    id number generated by default as identity primary key,
    name varchar(255)
);
create table articles(
    id number generated by default as identity primary key,
    title varchar(255),
    description clob,
    cate_id number,
    status number(1) default 1,
    constraint fk_articles_categories foreign key (cate_id) references categories(id)
);